### ISSUE TITLE
[FEAT] 마이페이지 문제리스트

### ISSUE THREAD

**Issue by minmunui** [Boksam/OnlineJudgeFE#10]
## **TODO(필수)**
- 현재의 내가 푼 문제리스트는 너무 단순합니다. 변경하십시오.
## **요청사항(부분 필수)**
- @hunsy9 특정 유저(username)가 해결하지 못한 문제 리스트를 반환하는 api를 작성해 주세요. 자세한 명세는 작업을 시작하면 저에게 요청하세요. 
## **제약사항(선택)**
- 각 문제는 버튼 형식으로 구현합니다.
- 드롭다운을 이용하여 필터를 적용할 수 있어야 합니다.
- 해결한 문제, 시도했지만 실패한 문제로 두 개의 탭으로 분리합니다.

**Comment by minmunui** [comment]
@hunsy9  props.js에 필요한 api를 정의해 두었습니다.
https://github.com/PNU-CSEP/CSEP_FE/blob/2017bac047bdef58090de6bbe9d9ebd2c63bb3cb/src/prop.js#L114

**Comment by hunsy9** [comment]
@minmunui  확인했습니다 감사합니다~
