### ISSUE TITLE
[FEAT] 회원가입 모달 드롭다운 기능 개발

### ISSUE THREAD

**Issue by hunsy9** [Boksam/OnlineJudgeFE#17]
## **TODO(필수)**
-  회원가입 모달 창의 단과대학, 학과 선택 드롭다운 **디자인(운영체제 기본 드롭다운 디자인)을 변경**해야 합니다.
-  회원가입 모달 창의 단과대학, 학과 선택 **API를 각 드롭다운에 연동**해야 합니다.
## **제약사항**
- API 요청시 모달 컴포넌트 내에서 이미 요청한 정보같은 경우는 캐싱해서 빈번한 api 호출을 막아주세요.
## **참고사항**
- 단과대학 API: "/college_list", method: **GET**
- 학과 API: "/department_list", method: **GET**
   - 단과대학 API에서 받은 **id(college_id)를 body에 담아 요청**해주세요. 
   - 예) ```{
   "college_id": 5
   }```

**Comment by minmunui** [comment]
@hunsy9 관련 api가 develop 브랜치에 구현되어 있나요?

**Comment by hunsy9** [comment]
@minmunui 
네 CSEP backend의 develop 브랜치에 구현이 되어있습니다.
혹시 api 호출이 안되는 상황이신가요?

**Comment by minmunui** [comment]
@hunsy9 아닙니다 잘 작동하네요 오늘 안으로 마무리해보겠습니다.

**Comment by minmunui** [comment]
@hunsy9 GET요청에 body에 query를 요청하는 것은 일반적으로 잘 사용되지 않는 패턴인 것 같습니다. 또한 기존 프로젝트에서 구현한 request 함수에서도 get요청에 body를 추가하는 기능은 구현되어 있지 않습니다. 기존의 패턴을 유지하고 싶은데, 혹시 백앤드에서 college_id를 request query에 담아 요청하는 방식으로 변경할 수 있나요?

**Comment by hunsy9** [comment]
쿼리스트링으로 요청을 할 수 있게 hotfix로 올리겠습니다

**Comment by hunsy9** [comment]
@minmunui
CSEP/develop에 작업해놨습니다!

**Comment by minmunui** [comment]
커밋에 이슈번호를 적는 것이 좋겠어요. 이렇게 링크가 되네요

**Comment by minmunui** [comment]
작업은 완료했으나... 정확한 테스트는 내일 해볼게요 늦은 밤에 고마워요 @hunsy9

**Comment by hunsy9** [comment]
@minmunui 네 저도 한번 테스트 해볼게요
