### ISSUE TITLE
[FEAT] 회원가입 modal 업데이트

### ISSUE THREAD

**Issue by minmunui** [Boksam/OnlineJudgeFE#23]
## **TODO(필수)**
현재의 회원가입모달에는 이상한 점이 많습니다. 너무 잦은 유효성검사 에러 및 에러 Toast, 고정된 이메일 input의 width 등 이러한 점들을 수정합니다.
## **제약사항(선택)**
iview의 기능들을 사용할 지 말지를 생각해야 합니다. iview는 커스텀 이렵기떄문에, 사이트 고유의 컴포넌트 만들기를 고려해야 합니다.

**Comment by hunsy9** [comment]
안그래도 현재 회원가입 모달에 오류가 너무 많았는데 좋아요

혹시 이메일에 @pusan.ac.kr도 고정시켜주실수 있나요?

**Comment by hunsy9** [comment]
새로운 컴포넌트를 만들때 각종 이벤트까지 만들어야하는데 여기서 시간이 많이 걸리지않을까요?
저는 iview를 그대로 쓰는게 맞다고 생각합니다.

**Comment by minmunui** [comment]
iview폐기는 한 번 견적 내보고 생각하겠습니다. 별도의 input을 제대로 만들어 두면 다른 곳에서도 편리하게 쓸 수 있을거 같아서...
도메인 고정도 해놓겠습니다. 대신 프론트단에서만 어느정도 식별이 가능할 것 같습니다.
